[project]
name = "gecs-00-jupyter"
description = "Test Jupyter notebook in VS Code"
version = "0.1.0"
channels = ['conda-forge']
platforms = ['linux-64', 'osx-64', 'osx-arm64', 'win-64']

[dependencies]
python = "~=3.10.0"
ipython = "*"
jupyterlab = "*"
loguru = "*"
matplotlib = "*"
notebook = "*"
numpy = "*"
pandas = "*"
ruff = "*"
scikit-learn = "*"
tqdm = "*"
typer = "*"
pip = "*"

[pypi-dependencies]
python-dotenv = "*"
src = { path = ".", editable = true }
